### ISSUE TITLE
The more --workers, the more likely execution fails

### ISSUE THREAD

**Issue by klemens-u** [theraser/blocksync#5]
The "--workers" option allows a great speedup of file transfer.

When using multiple workers from the command line, the more workers, the more likely the execution fails: (Extreme example with 16 workers)

```
Worker #13 caused ABORT
  File "/root/bin/blocksync.py", line 384, in <module>
Traceback (most recent call last):
  File "/root/bin/blocksync.py", line 384, in <module>
    server(dstdev, False, options)
  File "/root/bin/blocksync.py", line 105, in server
    size = int(sys.stdin.readline().strip())
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/root/bin/blocksync.py", line 384, in <module>
    server(dstdev, False, options)
  File "/root/bin/blocksync.py", line 105, in server
    size = int(sys.stdin.readline().strip())
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/root/bin/blocksync.py", line 384, in <module>
    server(dstdev, False, options)
  File "/root/bin/blocksync.py", line 105, in server
    size = int(sys.stdin.readline().strip())
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/root/bin/blocksync.py", line 384, in <module>
    server(dstdev, False, options)
  File "/root/bin/blocksync.py", line 105, in server
    size = int(sys.stdin.readline().strip())
ValueError: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/root/bin/blocksync.py", line 384, in <module>
```

Environment:

- Ubuntu 16.04 LTS Server
- Using kpartx to create a block device from an image file
- Command: 

/root/bin/blocksync.py '--extraparams=-p 2222' --cipher=aes256-ctr --blocksize=4194304 --workers=16 --script=/root/bin/blocksync.py /dev/loop1 root@example.com /srv/libvirt_images/myserver.root.img

**Comment by ct16k** [comment]
That may very well be. I've added the `--workers` option to help during a recovery, so it's was kind of a rushed job to bolt on parallelization, not the most reliable thing.

Have you tried using `--splay` to add a sleep interval between fork()s ? The remote server might be refusing too many connections at once (or simply not being able to negociate all those SSH connections in time).

**Comment by klemens-u** [comment]
Thanks, that seems to be the solution. I successfully tested a few blocksync executions with --workers=32 --splay=250.
250ms would be a sensible default. Do you see any negative side effects?

**Comment by ct16k** [comment]
Sounds OK to me.
